author: wizzledonker
database: false
description: Users must buy tickets before they are allowed to enter a train/cart.
main: me.wizzledonker.plugins.trainticket.Trainticket
name: TrainTicket
startup: postworld
version: '1.5c1.6.2'
softdepend: [Vault]
permissions:
  TrainTicket.exempt.boat:
    Description: Defines whether the player is exempt from ticket payment when entering boats
TrainTicket.exempt.cart:
    Description: Defines whether the player is exempt from ticket payment when entering carts
    Default: false
  TrainTicket.booth.use:
    Description: Defines whether the player can buy a ticket from a ticket booth
    Default: true
  TrainTicket.booth.create:
    Description: Defines whether the player can create a ticket booth
    Default: op